In [ ]:
from numpy import exp, array, random, dot


class NeuralNetwork():
    def __init__(self):
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        random.seed(2)

        # We model a single neuron, with 3 input connections and 1 output connection.
        # We assign random weights to a 3 x 1 matrix, with values in the range -1 to 1
        # and mean 0.
        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron).
            output = self.think(training_set_inputs)

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            # Adjust the weights.
            self.synaptic_weights += adjustment

    # The neural network thinks.
    def think(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        return self.__sigmoid(dot(inputs, self.synaptic_weights))

if __name__ == "__main__":

    #Intialise a single neuron neural network.
    neural_network = NeuralNetwork()

    print("Random starting synaptic weights: ")
    print(neural_network.synaptic_weights)

    # The training set. We have 4 examples, each consisting of 3 input values
    # and 1 output value.
    training_set_inputs = array([[1, 0, 0], [1, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 1], [0, 1, 0]])
    training_set_outputs = array([[0, 1, 1, 0, 1, 0]]).T

    # Train the neural network using a training set.
    # Do it 10,000 times and make small adjustments each time.
    neural_network.train(training_set_inputs, training_set_outputs, 100000)

    print("New synaptic weights after training: ")
    print(neural_network.synaptic_weights)

    # Test the neural network with a new situation.
    print("Considering new situation [1, 1, 1] -> ?: ")
    print(neural_network.think(array([1, 1, 1])))

In [ ]:
import random 

random.randint(1, 7)

In [ ]:
def conv_binary(n):
    binary = [0, 0, 0]
    if n >= 2**2:
        n -= 2**2
        binary[0] = 1
    if n >= 2**1:
        n -= 2**1
        binary[1] = 1
    if n >= 2**0:
        n -= 2**0
        binary[2] = 1
    return array(binary)

a = 7

print(a, "modulo 2 ==", round(neural_network.think(conv_binary(a))[0]))

In [2]:
from numpy import exp, array, random, dot


class NeuralNetwork():
    def __init__(self):
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        random.seed(2)

        # We model a single neuron, with 3 input connections and 1 output connection.
        # We assign random weights to a 3 x 1 matrix, with values in the range -1 to 1
        # and mean 0.
        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron).
            output = self.think(training_set_inputs)

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            # Adjust the weights.
            self.synaptic_weights += adjustment

    # The neural network thinks.
    def think(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        return self.__sigmoid(dot(inputs, self.synaptic_weights))

if __name__ == "__main__":

    #Intialise a single neuron neural network.
    neural_network = NeuralNetwork()

    print("Random starting synaptic weights: ")
    print(neural_network.synaptic_weights)

    # The training set. We have 4 examples, each consisting of 3 input values
    # and 1 output value.
    training_set_inputs = array([[1, 0, 0], [1, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 1], [0, 1, 0]])
    training_set_outputs = array([[0, 1, 1, 0, 1, 0]]).T

    # Train the neural network using a training set.
    # Do it 10,000 times and make small adjustments each time.
    neural_network.train(training_set_inputs, training_set_outputs, 100000)

    print("New synaptic weights after training: ")
    print(neural_network.synaptic_weights)

    # Test the neural network with a new situation.
    print("Considering new situation [1, 0, 0] -> ?: ")
    print(neural_network.think(array([1, 0, 1])))

Random starting synaptic weights: 
[[-0.1280102 ]
 [-0.94814754]
 [ 0.09932496]]
New synaptic weights after training: 
[[-5.39675214]
 [-5.39676267]
 [16.33506107]]
Considering new situation [1, 0, 0] -> ?: 
[0.99998224]


### Ideas for Neural network problems

- RGB colour guesser
- 21 questions type game (simplified?)
- Language detection
- Naughts and crosses 


##### Naughts and crosses
- matrix representation [[0,0,0],[0,0,0],[0,0,0]] (empty table)
- [[1,-1,-1],[0,1,0],[0,0,1]] (diagonal win)

In [3]:
print(array([[0,0,0],[0,0,0],[0,0,0]]))
print(array([[1,-1,-1],[0,1,0],[0,0,1]]))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1 -1 -1]
 [ 0  1  0]
 [ 0  0  1]]


- 9 bits of input (current table)
- 1 bit of output (location of move)
- learn to make optimal move
- collect data on optimal moves in many different situations (can do this by simulation in python and using memoisation)

In [4]:
from numpy import array, random
import numpy as np


board = array([['X','X','O'],['X', None,'O'],['X','X','O']])
print(board)

def check_win(board):
    """Function checks if the current board scenario is a win for Os and Xs.
    OUTPUT: (Boolean, Boolean)
            (Os win?, Xs win?)."""
    
    winnersO = []   # Initialising
    winnersX = []
    for colrow in range(3):
        
        if list(board[:,colrow]).count('O') == 3:   # Checking 1s wins (rows and columns)
            winnersO.append(True)
        else:
            winnersO.append(False)
        if list(board[colrow,:]).count('O') == 3:
            winnersO.append(True)
        else:
            winnersO.append(False)
        
        if list(board[:,colrow]).count('X') == 3:   # Checking 0s wins (rows and columns)
            winnersX.append(True)
        else:
            winnersX.append(False)
        if list(board[colrow,:]).count('X') == 3:
            winnersX.append(True)
        else:
            winnersX.append(False)

            
    if list([board[0,0], board[1,1], board[2,2]]).count('O') == 3:   # Checking 1s wins (diagonals)
        winnersO.append(True)
    else:
        winnersO.append(False)
    if list([board[0,2], board[1,1], board[2,0]]).count('O') == 3:
        winnersO.append(True)
    else:
        winnersO.append(False)
    
    if list([board[0,0], board[1,1], board[2,2]]).count('X') == 3:   # Checking 0s wins (diagonals)
        winnersX.append(True)
    else:
        winnersX.append(False)
    if list([board[0,2], board[1,1], board[2,0]]).count('X') == 3:
        winnersX.append(True)
    else:
        winnersX.append(False)
    
    
    return [any(winnersO), any(winnersX)]   # Check to see if any wins

check_win(board)

[['X' 'X' 'O']
 ['X' None 'O']
 ['X' 'X' 'O']]


[True, True]

In [5]:
board = np.full((3,3), None)

def make_moveO(board):
    """Makes a move for 1s at random.
    OUTPUT: Updated board."""
    if np.count_nonzero(board == None) == 0:   # Check if any moves possible
        return board
    
    play_position = random.randint(0, 3, 2)   # Produces a random position to play
    if board[play_position[0], play_position[1]] == None:
        board[play_position[0], play_position[1]] = 'O'   # If free space, claims that location
    else:
        make_moveO(board)   # If not, try again by re-calling the function
    
    return board


def make_moveX(board):
    """Makes a move for 0s at random.
    OUTPUT: Updated board."""
    if np.count_nonzero(board == None) == 0:
        return board
    
    play_position = random.randint(0, 3, 2)
    if board[play_position[0], play_position[1]] == None:
        board[play_position[0], play_position[1]] = 'X'
    else:
        make_moveX(board)
    
    return board

In [6]:
make_moveX(board)
print(board)
check_win(board)

[[None None None]
 [None None None]
 ['X' None None]]


[False, False]

In [7]:
def simulate_game():
    """Simulates a game of random moves. 
    OUTPUT: Final board, [1s win?, 0s win?]."""
    board = np.full((3,3), None)
    win = 0
    while win == 0:
        
        if np.count_nonzero(board == None) == 0:
            return board, [False, False]   # No winner
        
        make_moveO(board)
        win += sum(check_win(board))
        make_moveX(board)
        win += sum(check_win(board))
        
    if win == 1:
        return board, [False, True]   # 0s win
    
    if win > 1:
        return board, [True, False]   # 1s win

In [8]:
final_board, winner = simulate_game()
print(final_board, winner)

[['O' 'X' 'X']
 ['O' None 'X']
 ['O' 'O' 'X']] [True, False]


In [9]:
WINNING_MOVE = dict()   # Want to store the situations where you are 1 move away from winning

def simulate_game_winning_move():
    """Simulates a game of random moves. 
    OUTPUT: Final board, [Os win?, Xs win?]."""
    global WINNING_MOVE
    
    board = np.full((3,3), None)
    win = 0
    while win == 0:   # Each round
        
        if np.count_nonzero(board == None) == 0:
            return board, [False, False]   # No winner
        
        prev_board = tuple(board.flatten())   # Store the board before the next move (as flattened list)
        
        make_moveO(board)   # Make the move
        if sum(check_win(board)) == 1:   # Check if winning move
            current_board = tuple(board.flatten())
            
            if prev_board in WINNING_MOVE:  
                if list(current_board) not in list(WINNING_MOVE[prev_board]):
                    WINNING_MOVE[prev_board] = tuple(list(WINNING_MOVE[prev_board]) + list(current_board))   # Log before and after winning move
            else:     
                WINNING_MOVE[prev_board] = current_board
            return board, [True, False]   # Return as before
        
        make_moveX(board)
        if sum(check_win(board)) == 1:
            current_board = tuple(board.flatten())
            
            if prev_board in WINNING_MOVE:  
                if list(current_board) not in list(WINNING_MOVE[prev_board]):
                    WINNING_MOVE[prev_board] = tuple(list(WINNING_MOVE[prev_board]) + list(current_board))   # Log before and after winning move
            else:     
                WINNING_MOVE[prev_board] = current_board
            return board, [False, True]

In [10]:
simulate_game_winning_move()

(array([['O', 'X', 'O'],
        ['X', 'O', 'X'],
        ['X', 'O', 'O']], dtype=object),
 [True, False])

In [11]:
def simulate_game_winning_move():
    """Simulates a game of random moves. 
    OUTPUT: Final board, [Os win?, Xs win?]."""
    global WINNING_MOVE
    
    board = np.full((3,3), None)
    win = 0
    while win == 0:   # Each round
        
        if np.count_nonzero(board == None) == 0:
            return board, [False, False]   # No winner
        
        prev_board = tuple(board.flatten())   # Store the board before the next move (as flattened list)
        
        make_moveO(board)   # Make the move
        if sum(check_win(board)) == 1:   # Check if winning move
            current_board = tuple(board.flatten())
            
            if current_board in WINNING_MOVE:  
                if list(prev_board) not in list(WINNING_MOVE[current_board]):
                    WINNING_MOVE[current_board] = tuple(list(WINNING_MOVE[current_board]) + list(prev_board))   # Log before and after winning move
            else:     
                WINNING_MOVE[current_board] = prev_board
            return board, [True, False]   # Return as before
            
        
        make_moveX(board)
        if sum(check_win(board)) == 1:
            current_board = tuple(board.flatten())
            
            if current_board in WINNING_MOVE:  
                if list(prev_board) not in list(WINNING_MOVE[current_board]):
                    WINNING_MOVE[current_board] = tuple(list(WINNING_MOVE[current_board]) + list(prev_board))   # Log before and after winning move
            else:     
                WINNING_MOVE[current_board] = prev_board
            return board, [False, True]
            

In [12]:
for _ in range(100000):
    simulate_game_winning_move()

In [13]:
len(WINNING_MOVE)

943

In [17]:
board, win = simulate_game()
print(board, win)

[['X' 'O' 'X']
 ['X' 'O' 'O']
 ['X' 'O' None]] [True, False]


In [18]:
prev_options = list(WINNING_MOVE[tuple(board.flatten())])
number_options = len(prev_options)//9
#print(prev_options)
for i in range(number_options):
    particular = prev_options[9*i: 9*(i+1)]
    prev_board = array([particular[:3], particular[3: 6], particular[6:]])
    print(prev_board, "\n")

KeyError: ignored

In [19]:
# Getting many repeated boards in the dictionary...
# Need to check still useful to have key as winning board and value as boards leading to such win
# Find out why we have more 'None' values than expected

Is this change saved?

In [21]:
print("Test if changes saved")

Test if changes saved
